### ISSUE TITLE
Can't create first user account

### ISSUE THREAD

**Issue by godsgood33** [owlistic-notes/owlistic#106]
**Describe the bug**
Unable to create the first account on new install

**To Reproduce**
I'm sure I have a different install than intended
1. I'm using a shared postgres install...can connect to DB fine
2. Docker compose file posted below
3. Had to change host ports due to conflicts, but that should not stop communication internally
4. When attempting to create an account it responds either with a 404 error for `/api/v1/register` or a `Null check operator used on a null value`

**Expected behavior**
Create an account

**Host Server:**
- OS: Unraid 7.1.2
- Docker compose posted below

**Client Desktop:**
 - OS: Fedora 42
 - Browser: Chromium
 - Version: 137

```yaml
services:
  owlistic:
    image: ghcr.io/owlistic-notes/owlistic:latest
    container_name: owlistic
    ports:
      - "8280:8080"
    depends_on:
      - nats
    environment:
      - APP_ORIGINS=http://localhost*,http://server.home:8282,http://owlistic*,http://owlistic-app*
      - BROKER_ADDRESS=nats:4222
      - DB_HOST=192.168.1.3
      - DB_PORT=5433
      - DB_USER=owlistic
      - DB_PASSWORD={pwd}
      - DB_NAME=owlistic
      - JWT_SECRET={secret}
    networks:
      - server
      - events

  owlistic-app:
    image: ghcr.io/owlistic-notes/owlistic-app:latest
    container_name: owlistic-app
    environment:
      - JWT_SECRET={secret}
    ports:
      - "8282:80"
    depends_on:
      - owlistic

  nats:
    image: nats
    container_name: owlistic-nats
    command:
      - --http_port
      - "8222"
      - -js
      - -sd
      - /var/lib/nats/data
    ports:
     - "4222:4222"
     - "8222:8222"
    volumes:
      - nats_data:/var/lib/nats/data
    networks:
      - events

volumes:
  nats_data:

networks:
  server:
    driver: bridge
  events:
    driver: bridge
```
